# Generated by Django 4.2.7 on 2025-08-02 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_carrier_created_by_trip_current_location_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='eldlog',
            name='fuel_consumed',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Fuel consumed in gallons', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='eldlog',
            name='total_engine_hours',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Total engine hours for the day', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='eldlog',
            name='total_idle_hours',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Total engine idle hours for the day', max_digits=10, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='eldlog',
            unique_together={('trip', 'date')},
        ),
    ]
